### ISSUE TITLE
Cannot launch generative_data_prep from different directory

### ISSUE THREAD

**Issue by rraju1** [sambanova/generative_data_prep#57]
I tried to install and launch the data prep command from a different directory that I cloned and I got this error. 

`
Traceback (most recent call last):
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/site-packages/generative_data_prep/__main__.py", line 300, in <module>
    logging.config.fileConfig("configs/logger.conf")
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/import/ml-sc-scratch1/ravir/miniconda3/envs/essentialai/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
`

**Comment by snova-zoltanc** [comment]
Doen with PR: https://github.com/sambanova/generative_data_prep/pull/58
